### ISSUE TITLE
ugit does not handle 0 length files during backup

### ISSUE THREAD

**Issue by jouellnyc** [turfptax/ugit#15]
Howdy. Great tool. 

"Out of the box", I ran a `ugit.backup()`. I legitimately have a zero length file as an status  indicator. That makes the back up fail:

```
>>> ugit.backup()

<snip>

/appsetup/setup.py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "ugit.py", line 225, in backup
  File "ugit.py", line 126, in build_internal_tree
  File "ugit.py", line 134, in add_to_tree
  File "ugit.py", line 131, in add_to_tree
OSError: 20

```  

I am not proposing to back up those files but perhaps it could continue the backup.

**Comment by turfptax** [comment]
Ok, will work on this right away. Needed an excuse to finish writing the restore functionality.

**Comment by turfptax** [comment]
Ok, working on the Dev branch to see if I can fix this.

**Comment by turfptax** [comment]
Working on the Dev branch to solve this this weekend if anyone wants to test it.

**Comment by dog42** [comment]
HeyHo, 

I also get the **OSError: 20** on backup and also on pull.
I guess the error occures because the `is_directory()` function doesn't check correctly.
As the **OSError:  20** says:  "uerrno.ENOTDIR | 20 | Not a directory" ([ref](https://mpython.readthedocs.io/en/master/library/pythonStd/uerrno.html)),
when it try the `listedir()` function one file whit `st_mtime == 0`.

I solved the problem with a fix in the `is_directory()` (l. 165):

Instead of checking the `st_mtime` for zero:
`return (os.stat(file)[8] == 0)`

I check if the right bit in `st_mode` says it is a dir ([ref](https://man7.org/linux/man-pages/man7/inode.7.html)):
`return (os.stat(file)[0] & 0xc000 == 0x4000)`

hope that helps ;)
