### ISSUE TITLE
new files blank after update

### ISSUE THREAD

**Issue by turfptax** [turfptax/ugit#5]
Some ESP32 boards show blank files after the update.

Boards show this error:

Traceback (most recent call last):
  File "<stdin>", line 13, in <module>
  File "ugit.py", line 61, in pull_all
  File "ugit.py", line 165, in pull_git_tree
  File "urequests.py", line 180, in get
  File "urequests.py", line 93, in request
OSError: 16

**Comment by turfptax** [comment]
Happens on ESP32 when REPL environment updates through REPL prompt after ugit.py update.

**Comment by turfptax** [comment]
Mostly wireless issue solved.
